# Generated by Django 3.0.5 on 2020-06-13 00:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('max_number_of_judgments', models.IntegerField()),
                ('strategy', models.CharField(choices=[('doc', 'Document (CAL)'), ('para', 'Paragraph (CAL)'), ('doc_scal', 'Document (S-CAL)'), ('para_scal', 'Paragraph (S-CAL)')], max_length=64)),
                ('show_full_document_content', models.BooleanField()),
                ('is_shared', models.BooleanField(blank=True, default=False, null=True)),
                ('timespent', models.FloatField(default=0)),
                ('last_activity', models.FloatField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('disallow_search', models.BooleanField(blank=True, default=False, null=True)),
                ('disallow_CAL', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
