# Generated by Django 3.0.5 on 2021-01-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_max_number_of_judgments_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='strategy',
            field=models.CharField(choices=[('doc_scal', 'Document (S-CAL)')], default='doc_scal', max_length=64),
        ),
    ]
