# Generated by Django 3.0.5 on 2021-01-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210127_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='strategy',
        ),
    ]
