# Generated by Django 3.0.5 on 2021-01-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_session_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='strategy',
            field=models.CharField(choices=[('doc_scal', 'Document (S-CAL)')], default='doc_scal', max_length=64),
        ),
    ]
