# Generated by Django 3.0.5 on 2021-02-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='q1',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q2',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='questions',
            name='q3',
            field=models.CharField(max_length=512),
        ),
    ]
