# Generated by Django 3.0.5 on 2021-02-05 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210205_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='education_other',
        ),
        migrations.RemoveField(
            model_name='demographics',
            name='gender',
        ),
    ]
