# Generated by Django 3.0.5 on 2021-02-05 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210205_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographics',
            name='education',
        ),
        migrations.AddField(
            model_name='demographics',
            name='gender',
            field=models.CharField(default=-1, max_length=512),
            preserve_default=False,
        ),
    ]
