# Generated by Django 3.0.5 on 2021-02-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210205_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographics',
            name='education',
            field=models.CharField(default='na', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographics',
            name='education_other',
            field=models.CharField(default='na', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographics',
            name='study',
            field=models.CharField(default='na', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demographics',
            name='study_other',
            field=models.CharField(default='na', max_length=512),
            preserve_default=False,
        ),
    ]
