# Generated by Django 3.0.5 on 2021-02-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210207_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='topic',
            field=models.CharField(max_length=512),
        ),
    ]
