# Generated by Django 3.0.5 on 2020-06-13 00:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=512)),
                ('doc_title', models.TextField()),
                ('doc_CAL_snippet', models.TextField()),
                ('doc_search_snippet', models.TextField()),
                ('query', models.TextField(blank=True, null=True)),
                ('relevance', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(blank=True, max_length=64, null=True)),
                ('search_query', models.TextField(blank=True, null=True)),
                ('ctrl_f_terms_input', models.TextField(blank=True, null=True)),
                ('found_ctrl_f_terms_in_title', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('found_ctrl_f_terms_in_summary', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('found_ctrl_f_terms_in_full_doc', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True)),
                ('timeVerbose', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True, verbose_name='History')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
            ],
        ),
    ]
