# Generated by Django 3.0.5 on 2020-06-13 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judgment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='judgment',
            unique_together={('user', 'doc_id', 'session')},
        ),
        migrations.AlterIndexTogether(
            name='judgment',
            index_together={('user', 'doc_id', 'session')},
        ),
    ]
