# Generated by Django 3.0.5 on 2020-09-30 19:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judgment', '0004_auto_20200928_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgment',
            name='other_criteria',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
