# Generated by Django 3.0.5 on 2021-01-21 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_query_searchresult_serpclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='num_display',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='page_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
