# Generated by Django 3.0.5 on 2020-12-20 16:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20200612_2039'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stratum_size', models.IntegerField()),
                ('stratum_num', models.IntegerField()),
                ('sample_size', models.IntegerField()),
                ('T', models.IntegerField()),
                ('N', models.IntegerField()),
                ('R', models.IntegerField()),
                ('sampled_docs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list)),
                ('stratum_docs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'stratum_num', 'session')},
                'index_together': {('user', 'stratum_num', 'session')},
            },
        ),
    ]
